title: UIDRRO's Website
#email: email@domain.tld
description: Website used for shenanigans.
#baseurl: "" the subpath of your site, e.g. /blog
url: https://uidrro.dev/
twitter_username: uidrro
github_username:  uidrro

theme: just-the-docs

aux_links:
  Template Repository: https://github.com/uidrro/uidrro.github.io
#  "This website":"https://uidrro.dev/"
aux_links_new_tab: false

logo: "https://avatars.githubusercontent.com/u/76664712?v=4"
favicon_ico: "/assets/images/favicon.ico"
search_enabled: true
search:
  heading_leevel: 3
  previews: 5
  preview_words_before: 10
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: false
  button: false
  #focus_shortcut_key: 'f'

nav_enabled: true
nav_fold: true

heading_anchors: true
color_scheme: dark

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "~/_posts/"
    output: true
just_the_docs:
  collections:
    docs:
      name: Docs
    posts:
      name: Posts

footer_content: "UIDRRO"
last_edit_timestamp: true
last_edit_time_format: "%F at %T:%L"
  #https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
